### ISSUE TITLE
GitHub and JIRA issue script should handle multiple issue mentions per message

### ISSUE THREAD

**Issue by hferentschik** [minishift/minibot#13]

**Comment by LalatenduMohanty** [comment]
@hferentschik mentioned the we might have to fix around https://github.com/minishift/minibot/blob/master/scripts/github-links.coffee#L19

**Comment by hferentschik** [comment]
Actually more around here - https://github.com/minishift/minibot/blob/master/scripts/github-links.coffee#L22. It might be that there are already multiple captures and they just need to be handled in a loop

**Comment by LalatenduMohanty** [comment]
I think we should do something like this in coffee script
```
while ((id = res.match[1]) !== null) {


    github.get "repos/minishift/minishift/issues/" + id, (issue) ->
      out = ""
      if /pull/.test(issue.html_url)
      	out = out + "PR - "
      out = out + issue.title + ' (' + issue.state  + ') - ' + issue.html_url
      res.send out
    }
```

**Comment by hferentschik** [comment]
Resolved.
