### ISSUE TITLE
Only notify to IRC on build failure 

### ISSUE THREAD

**Issue by budhrg** [minishift/minibot#29]
Currently, we get IRC notifications when the builds succeed/fails.

This might be lots of noise in IRC. We should notify only when the build fails.

**Comment by hferentschik** [comment]
Ok :-). @budhrg if you start working on this let me know or assign it to yourself. Otherwise I might fix it when I get a few free cycles. Pretty straight forward.

**Comment by hferentschik** [comment]
Merged via pull request #31
