### ISSUE TITLE
Remind for archaeologist after standup

### ISSUE THREAD

**Issue by budhrg** [minishift/minibot#32]
The idea is to notify necromancer during standup every Monday as a reminder.

The names are:
- @LalatenduMohanty 
- @praveenkumar 
- @gbraad 
- @hferentschik 
- @budhrg
- @amitkrout 
- @agajdosi

**Comment by gbraad** [comment]
? why do I need a reminder for something I do daily... ?

**Comment by budhrg** [comment]
> ? why do I need a reminder for something I do daily... ?

We appreciate that you do it daily but as a team that effort should be divided across. :smile:

**Comment by hferentschik** [comment]
@budhrg thanks for creating the issue.

**Comment by LalatenduMohanty** [comment]
There should be a way to override to move to the next auto selected in case someone is out of office for that week.

**Comment by hferentschik** [comment]
> There should be a way to override to move to the next auto selected in case someone is out of office for that week.

Of course. Some sort of manual intervention is needed.

**Comment by hferentschik** [comment]
Merged via pull request #33
