### ISSUE TITLE
Make minibot use a github API token

### ISSUE THREAD

**Issue by anjannath** [minishift/minibot#44]
_minibot_ needs access to https://api.github.com for fetching info about issues, and its ability to do that is affected by the rate limit on the endpoint.

we can set an env variable say `MINIBOT_GITHUB_API_TOKEN` and this will be used to make authenticated requests to github.

**Comment by anjannath** [comment]
Looks like the script use for resolving issues already had that feature, just need to export an env variable `HUBOT_GITHUB_TOKEN`

https://github.com/iangreenleaf/githubot

**Comment by budhrg** [comment]
Correct @anjannath
